# Generated by Django 4.2.4 on 2023-08-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('belongs_to', models.CharField(max_length=255)),
                ('correct', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='member',
            old_name='football_quiz',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='general_quiz',
            new_name='lastname',
        ),
    ]
