# Generated by Django 4.2.4 on 2023-08-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_question_f_question_g_delete_answer_delete_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_f',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='question_g',
            name='answers',
        ),
        migrations.AddField(
            model_name='question_f',
            name='answer1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question_f',
            name='answer2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question_f',
            name='answer3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question_f',
            name='answer4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question_g',
            name='answer1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question_g',
            name='answer2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question_g',
            name='answer3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question_g',
            name='answer4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question_f',
            name='correct_answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question_f',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question_g',
            name='correct_answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question_g',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
